feat(playerPositions): update playerPositions
kjeldsen-game/monorepo pull request #74
Opened 2023-11-24 03:38 UTC by Javier-Lorenzo-Carrion

Upgrade PlayerPositions and make sure we have the same positions in the entire main-service (look TODO with names please).

2023-11-24 06:18 UTC, DaliVG commented on services/main-service/infrastructure/src/test/java/com/kjeldsen/integration/player/PlayerPositionTendencyApiIT.java
Vale habrá cambiado el orden

2023-11-24 06:20 UTC, DaliVG approved these changes

2023-11-30 13:47 UTC, sheyko94 requested changes

2023-11-30 13:47 UTC, sheyko94 commented on services/main-service/infrastructure/src/test/java/com/kjeldsen/integration/player/PlayerPositionTendencyApiIT.java
> +//import com.kjeldsen.player.rest.model.PlayerPosition; // TODO DALI E IVAN ESTO ME ESTABA DANDO ERROR Y REQUERÍA UN TIPO REST EN PLAYERPOSITION Y TENÍA UN DOMAIN Y NO SE PORQUE
si funciona sin el import, borra la linea entera y ya :D

2023-11-30 13:47 UTC, sheyko94 commented on services/main-service/infrastructure/src/test/java/com/kjeldsen/integration/player/PlayerPositionTendencyApiIT.java
> +                /*new PlayerPositionTendencyResponse() // TODO MUDO COMPROBAR POR QUE ES EL UNICO DIFERENTE
se te olvido esto?

2023-11-30 14:21 UTC, Javier-Lorenzo-Carrion commented on services/main-service/infrastructure/src/test/java/com/kjeldsen/integration/player/PlayerPositionTendencyApiIT.java
> +                /*new PlayerPositionTendencyResponse() // TODO MUDO COMPROBAR POR QUE ES EL UNICO DIFERENTE
No exactamente. He comentado esas líneas porque ya no sé si venían de atrás o que yo modificando metí la pata en algún momento, pero ¿no te parece que está fuera de lugar? ¿como que ahí no va? Quizá fui yo que modificando algo dupliqué ese código de otro sitio y luego me di cuenta (si te fijas esas líneas son distintas al resto)

2023-11-30 14:25 UTC, sheyko94 commented on services/main-service/infrastructure/src/test/java/com/kjeldsen/integration/player/PlayerPositionTendencyApiIT.java
> +                /*new PlayerPositionTendencyResponse() // TODO MUDO COMPROBAR POR QUE ES EL UNICO DIFERENTE
ah si, esta en la linea 124 ya :D

2023-11-30 14:37 UTC, Javier-Lorenzo-Carrion commented on services/main-service/infrastructure/src/test/java/com/kjeldsen/integration/player/PlayerPositionTendencyApiIT.java
> +                /*new PlayerPositionTendencyResponse() // TODO MUDO COMPROBAR POR QUE ES EL UNICO DIFERENTE
Vale, lo elimino y actualizo la pull

2023-11-30 14:56 UTC, sheyko94 approved these changes

2023-12-01 15:11 UTC, merged